01 REM PROGRAMMA CHE SOMMA DUE NUMERI
02 REM CHIEDENDO DI INSERIRE PRIMA IL PRIMO OPERANDO
03 REM E POI IL SECONDO OPERANDO
10 INPUT "INSERISCI UN NUMERO : "; A
20 INPUT "INSERISCI UN NUMERO : "; B
30 PRINT A+B